import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  containerBlock: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#181818',
    paddingBottom: 30,
  },
  container: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#181818',
  },
  containerScroll: {
    width: 400,
    height: 400,
    backgroundColor: '#181818',
  },
  nextScreenButton: {
    marginBottom: 10,
    paddingHorizontal: 80,
    borderRadius: 100,
    backgroundColor: '#343333',
  },
  addButton: {
    marginBottom: 10,
    marginHorizontal: 10,
    marginTop: 15,
    height: 70,
    width: 70,
    borderRadius: 80,
    backgroundColor: '#343333',
  },
  sortButton: {
    marginBottom: 5,
    marginTop: 10,
    height: 20,
    width: 70,
    backgroundColor: '#343333',
  },
  sortText: {
    color: '#b1b4b1',
    textAlign: 'center',
    paddingTop: 5,
    fontSize: 20,
    // fontWeight: '700',
  },
  addText: {
    color: '#b1b4b1',
    textAlign: 'center',
    paddingTop: 15,
    fontSize: 30,
    fontWeight: '700',
  },
  logoutButton: {
    marginHorizontal: 20,
    paddingHorizontal: 60,
    marginTop: 20,
    borderRadius: 5,
    backgroundColor: '#fd5e53',
  },
  loginText: {
    color: '#b1b4b1',
    textAlign: 'center',
    paddingHorizontal: 80,
    fontSize: 16,
    fontWeight: '700',
  },
  loggedInText: {
    textAlign: 'center',
    paddingTop: 145,
    fontWeight: '600',
  },
  movieBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 250,
    width: 330,
    borderRadius: 10,
    borderColor: '#4f4e4e',
    borderWidth: 1,
    marginVertical: 20,
  },
  blockName: {
    textAlign: 'center',
    marginBottom: 5,
    paddingVertical: 5,
    paddingLeft: 5,
    color: '#838583',
    fontSize: 13,
  },
  blockNameBox: {
    textAlign: 'center',
    height: 20,
    width: 330,
    borderRadius: 20,
    backgroundColor: '#4f4e4e',
  },
  movieCentralBlock: {
    flexDirection: 'row',
  },
  centralBlockTextBox: {
    textAlign: 'center',
    height: 20,
    width: 100,
    marginHorizontal: 5,
    borderRadius: 20,
    backgroundColor: '#4f4e4e',
  },
  centralBlockGroup: {
    flexDirection: 'column',
  },
  blockAboutMovie: {
    textAlign: 'center',
    height: 50,
    width: 330,
    borderRadius: 20,
    backgroundColor: '#4f4e4e',
  },
  deleteButton: {
    paddingHorizontal: 10,
    marginVertical: 15,
    borderRadius: 5,
    backgroundColor: '#fd5e53',
  },
  deleteText: {
    color: '#d8dad8',
    textAlign: 'center',
    fontSize: 16,
  },
});
